version: "3.1"
services:
  backend:
    image: zamperetti/people-register
    ports:
      - 8080:8080
  frontend:
    image: zamperetti/people-register-ui
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_URL: "http://localhost:8080"
      NODE_ENV: development
    stdin_open: true
    tty: true
    depends_on:
      - backend